spring.application.name=ega

# Configuration du serveur
server.port=8080

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ega_bank
spring.datasource.username=ega_user
spring.datasource.password=ega_password
spring.datasource.driver-class-name=org.mysql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT
jwt.secret=uneCleSecreteTresLongueEtSecuriseePourLaSignatureDesTokensJWT123456789
jwt.expiration=86400000

# Configuration des logs
logging.level.com.ega.banking=DEBUG
logging.level.org.springframework.security=DEBUG

# Configuration CORS (on verra plus tard pour Angular)
spring.web.cors.allowed-origins=http://localhost:4200